-- ============================================
-- Funcion que retorna una resultado
-- ============================================

CREATE TYPE SCOTT.MYTYPE AS OBJECT(
  FIELD1 NUMBER,
  FIELD2 VARCHAR2(50)
);

CREATE TYPE SCOTT.MYTYPELIST AS TABLE OF SCOTT.MYTYPE;


CREATE OR REPLACE FUNCTION SCOTT.FN_GET_EMPS
RETURN SCOTT.MYTYPELIST PIPELINED
IS
  V_MYTYPE MYTYPE;
BEGIN
  FOR R IN (SELECT EMPNO, ENAME FROM SCOTT.EMP) LOOP
  
    V_MYTYPE := MYTYPE( R.EMPNO, R.ENAME );
    
    PIPE ROW (V_MYTYPE);
    
  END LOOP;
  
  RETURN;
END FN_GET_EMPS;


Select * From Table(SCOTT.FN_GET_EMPS);


----------------------------------------------------

CREATE OR REPLACE FUNCTION SCOTT.FN_GET_EMPS2
( CODDEPT NUMBER )
RETURN SCOTT.MYTYPELIST PIPELINED
IS
  V_MYTYPE MYTYPE;
BEGIN
     FOR R IN (SELECT EMPNO, ENAME FROM SCOTT.EMP WHERE DEPTNO = CODDEPT) LOOP
         V_MYTYPE := MYTYPE( R.EMPNO, R.ENAME );
         PIPE ROW (V_MYTYPE);
     END LOOP;
     RETURN;
END FN_GET_EMPS2;


Select FIELD1 CODIGO, FIELD2 NOMBRE
From Table(SCOTT.FN_GET_EMPS2(20));


