INSERT INTO SIG_TM_TIPO_PAGO (id_tipo_pago,nombre,estado) values ('1','Efectivo','1');
INSERT INTO SIG_TM_TIPO_PAGO (id_tipo_pago,nombre,estado) values ('2','Targeta Credito','1');

INSERT INTO SIG_TM_ESTABLECIMIENTOS (id_establecimiento,nom_establecimiento,direccion,telefono,estado)
VALUES(1,'LA VICTORIA','AV. MANCO CAPAC 218','7456568',1) ;


INSERT INTO sig_tm_pacientes
          (id_paciente,tip_documento,num_documento,nombres,ape_paterno,ape_materno,sexo,direccion)
   VALUES
          ('1', '1', '72630837','PABLO' ,'QUEZADA', 'HUERTA', 'M','AV. XQAZSX 450');
 

INSERT INTO SIG_TD_DETALLES(ID_DETALLE,NUM_TICKET,ID_CONSULTORIO,PRECIO) VALUES('1','1','1',80);
INSERT INTO SIG_TD_DETALLES(ID_DETALLE,NUM_TICKET,ID_CONSULTORIO,PRECIO) VALUES('2','1','4',70);
INSERT INTO SIG_TD_DETALLES(ID_DETALLE,NUM_TICKET,ID_CONSULTORIO,PRECIO) VALUES('3','1','5',100);

INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(1,'MEDICINA GENERAL',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(2,'ENFERMERIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(3,'OBSTETRICIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(4,'ODONTOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(5,'LABORATORIO',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(6,'ADMICION',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(7,'ELECTROCARDIOGRAMA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(8,'GINECOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(9,'PSICOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(10,'GASTROENTEROLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(11,'ECOGRAFIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(12,'OTORRINOLARINGOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(13,'COMPUTO',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(14,'ANATOMIA PATOLOGICA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(15,'ATENCION PREHOSPITALARIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(16,'CIRUGIA DE CABEZA Y CUELLO',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(17,'CIRUGIA GENERAL',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(18,'CIRUGIA PEDIATRICA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(19,'CRECIMIENTO Y DESARROLLO',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(20,'ENDOCRINOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(21,'ESTRATEGIAS SANITARIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(22,'GERIATRIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(23,'HEMATOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(24,'MEDICINA NUCLEAR',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(25,'NEFROLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(26,'NEUROCIRUGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(27,'OBSTETRICIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(28,'PEDIATRIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(29,'TOPICO',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(30,'URGENCIAS Y EMERGENCIAS MEDICAS ',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(31,'ADMINISTRACION',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(32,'CENTRO QUIRURGICO',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(33,'INMUNOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(34,'TRASLADO EN AMBULANCIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(35,'UNIDAD DE TRATAMIENTO DEL DOLOR',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(36,'UNIDAD DE TRATAMIENTO LASER',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(37,'UNIDAD DE TRATAMIENTO DE LA INFERTILIDAD',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(38,'ADMINISTRACION HOSPITALARIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(39,'MEDICINA HIPERBARICA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(40,'AMBULANCIA EVENTOS',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(41,'RADIOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(42,'PODOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(43,'CARDIOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(44,'CIRUGIA CARDIOVASCULAR',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(45,'ECOGRAFIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(46,'MEDICINA GENERAL',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(47,'MASTOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(48,'MEDICINA INTERNA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(49,'DERMATOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(50,'CIRUGIA PLASTICA, ESTETICA Y REPARADORA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(51,'GASTROENTEROLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(52,'NEUMOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(53,'NEUROLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(54,'LABORATORIO CLINICO',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(55,'GINECOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(56,'NUTRICION',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(57,'ODONTOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(58,'OFTALMOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(59,'MEDICINA FISICA Y REHABILITACION',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(60,'MAMOGRAFIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(61,'PSICOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(62,'UROLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(63,'TOMOGRAFIA ESPIRAL MULTICORTE',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(64,'RESONANCIA MAGNETICA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(65,'PSIQUIATRIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(66,'OTORRINOLARINGOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(67,'ONCOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(68,'REUMATOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(69,'DENSITOMETRIA OSEA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(70,'TRAUMATOLOGIA',1);
INSERT INTO SIG_TM_CONSULTORIO(ID_CONSULTORIO,NOM_CONSULTORIO,ESTADO) VALUES(71,'MEDICINA DEL NIÑO',1);

