CREATE TABLE SCOTT.SIG_TM_PACIENTES (
"ID_PACIENTE" NUMBER NOT NULL,
"TIP_DOCUMENTO" CHAR(1 ) ,
"NUM_DOCUMENTO" VARCHAR2(15) ,
"NOMBRES" VARCHAR2(50) ,
"APE_PATERNO" VARCHAR2(50) ,
"APE_MATERNO" VARCHAR2(50) ,
"SEXO" CHAR NULL,
"DIRECCION" VARCHAR2(50) ,
 CONSTRAINT  PK_SIG_TM_PACIENTES PRIMARY KEY ("ID_PACIENTE") 
);
ALTER TABLE SCOTT.SIG_TM_PACIENTES ADD UNIQUE ("NUM_DOCUMENTO");

create sequence scott.sec_pacientes
  start with 1
  increment by 1
  MAXVALUE 99999
  minvalue 1;
  
 CREATE TABLE SCOTT.SIG_TM_ESTABLECIMIENTOS (
"ID_ESTABLECIMIENTO" NUMERIC NOT NULL,
"NOM_ESTABLECIMIENTO" VARCHAR2(50) NULL,
"DIRECCION" VARCHAR2(50) NULL,
"TELEFONO" NUMBER NULL,
"ESTADO" CHAR(1) NULL,
CONSTRAINT  PK_SIG_TM_ESTABLECIMIENTOS PRIMARY KEY (ID_ESTABLECIMIENTO) 
); 
CREATE TABLE SCOTT.SIG_TM_TIPO_PAGO (
"ID_TIPO_PAGO" NUMBER NOT NULL,
"NOMBRE" VARCHAR2(100) NULL,
"ESTADO" CHAR(1 ) NULL,
CONSTRAINT  PK_SIG_TM_TIPO_PAGO PRIMARY KEY ("ID_TIPO_PAGO") 
);

CREATE TABLE SCOTT.SIG_TC_TICKETS (
"NUM_TICKET" NUMBER NOT NULL,
"FEC_EMISION" DATE NULL,
"ID_ESTABLECIMIENTO" NUMBER NULL,
"ID_PACIENTE" NUMBER NULL,
"ID_TIPO_PAGO" NUMBER NULL,
"PRECIO" NUMERIC NULL,
"ESTADO" CHAR(1) NULL,
CONSTRAINT  PK_SIG_TC_TICKETS  PRIMARY KEY ("NUM_TICKET"),
CONSTRAINT FK_TICKETS_ESTABLEC 
FOREIGN KEY (ID_ESTABLECIMIENTO) REFERENCES SCOTT.SIG_TM_ESTABLECIMIENTOS (ID_ESTABLECIMIENTO),
CONSTRAINT FK_TICKETS_PACIENTES 
FOREIGN KEY (ID_PACIENTE) REFERENCES SCOTT.SIG_TM_PACIENTES (ID_PACIENTE),
CONSTRAINT FK_TICKETS_TIPO_PAGO 
FOREIGN KEY (ID_TIPO_PAGO) REFERENCES SCOTT.SIG_TM_TIPO_PAGO (ID_TIPO_PAGO)
);
  create sequence scott.sec_det_tickets
  start with 1
  increment by 1
  MAXVALUE 99999
  minvalue 1;
 
 CREATE TABLE SCOTT.SIG_TM_CONSULTORIO (
"ID_CONSULTORIO" NUMBER NOT NULL,
"NOM_CONSULTORIO" VARCHAR2(100) NULL,
"DESCRIPCION" VARCHAR2(100) NULL,
"ESTADO" CHAR(1) NULL,
CONSTRAINT SIG_TM_CONSULTORIO PRIMARY KEY ("ID_CONSULTORIO") 
);
  
CREATE TABLE SCOTT.SIG_TD_DETALLES (
"ID_DETALLE" NUMBER NOT NULL,
"NUM_TICKET" NUMBER NULL,
"ID_CONSULTORIO" NUMBER NULL,
"PRECIO" NUMBER NULL,
CONSTRAINT SIG_TD_DETALLES PRIMARY KEY ("ID_DETALLE"),
CONSTRAINT FK_DETALLES_TICKETS 
FOREIGN KEY (NUM_TICKET) REFERENCES SCOTT.SIG_TC_TICKETS (NUM_TICKET),
CONSTRAINT FK_DETALLES_CONSULTORIOS 
FOREIGN KEY (ID_CONSULTORIO) REFERENCES SCOTT.SIG_TM_CONSULTORIO (ID_CONSULTORIO)
);
--DROP TABLE SCOTT.SIG_TC_TICKETS;
