
--CREAR CRUD PARA TABLA PRODUCTOS
CREATE OR REPLACE PACKAGE ADMIN_FARMACIA.PKGCRUD AS
  PROCEDURE CREAR_PRODUCTOS (
    V_COD_CATEGORIA      IN  ADMIN_FARMACIA.PRODUCTO.COD_CATEGORIA%TYPE,
    V_COD_ACCION         IN  ADMIN_FARMACIA.PRODUCTO.COD_ACCION%TYPE,
    V_COD_LABORATORIO    IN  ADMIN_FARMACIA.PRODUCTO.COD_LABORATORIO%TYPE,
    V_NOM_PRODUCTO       IN  ADMIN_FARMACIA.PRODUCTO.NOM_PRODUCTO%TYPE,
    V_PRECIO_COSTO       IN  ADMIN_FARMACIA.PRODUCTO.PRECIO_COSTO%TYPE,
    V_PRECIO_UNIDAD      IN  ADMIN_FARMACIA.PRODUCTO.PRECIO_UNIDAD%TYPE,
    V_FECHA_VCTO         IN  ADMIN_FARMACIA.PRODUCTO.FECHA_VCTO%TYPE,
    V_STOCK              IN  ADMIN_FARMACIA.PRODUCTO.STOCK%TYPE,
    V_STOCK_MIN          IN  ADMIN_FARMACIA.PRODUCTO.STOCK_MIN%TYPE
  );

  PROCEDURE ACTUALIZAR_PRODUCTOS (
    V_COD_PRODUCTO       IN  ADMIN_FARMACIA.PRODUCTO.COD_PRODUCTO%TYPE,
    V_COD_CATEGORIA      IN  ADMIN_FARMACIA.PRODUCTO.COD_CATEGORIA%TYPE,
    V_COD_ACCION         IN  ADMIN_FARMACIA.PRODUCTO.COD_ACCION%TYPE,
    V_COD_LABORATORIO    IN  ADMIN_FARMACIA.PRODUCTO.COD_LABORATORIO%TYPE,
    V_NOM_PRODUCTO       IN  ADMIN_FARMACIA.PRODUCTO.NOM_PRODUCTO%TYPE,
    V_PRECIO_COSTO       IN  ADMIN_FARMACIA.PRODUCTO.PRECIO_COSTO%TYPE,
    V_PRECIO_UNIDAD      IN  ADMIN_FARMACIA.PRODUCTO.PRECIO_UNIDAD%TYPE,
    V_FECHA_VCTO         IN  ADMIN_FARMACIA.PRODUCTO.FECHA_VCTO%TYPE,
    V_STOCK              IN  ADMIN_FARMACIA.PRODUCTO.STOCK%TYPE,
    V_STOCK_MIN          IN  ADMIN_FARMACIA.PRODUCTO.STOCK_MIN%TYPE
  );
  PROCEDURE ELIMINAR_PRODUCTOS (
    V_COD_PRODUCTO       IN  ADMIN_FARMACIA.PRODUCTO.COD_PRODUCTO%TYPE
  );
END PKGCRUD;
/

CREATE OR REPLACE PACKAGE BODY ADMIN_FARMACIA.PKGCRUD AS
  PROCEDURE CREAR_PRODUCTOS (
    V_COD_CATEGORIA      IN  ADMIN_FARMACIA.PRODUCTO.COD_CATEGORIA%TYPE,
    V_COD_ACCION         IN  ADMIN_FARMACIA.PRODUCTO.COD_ACCION%TYPE,
    V_COD_LABORATORIO    IN  ADMIN_FARMACIA.PRODUCTO.COD_LABORATORIO%TYPE,
    V_NOM_PRODUCTO       IN  ADMIN_FARMACIA.PRODUCTO.NOM_PRODUCTO%TYPE,
    V_PRECIO_COSTO       IN  ADMIN_FARMACIA.PRODUCTO.PRECIO_COSTO%TYPE,
    V_PRECIO_UNIDAD      IN  ADMIN_FARMACIA.PRODUCTO.PRECIO_UNIDAD%TYPE,
    V_FECHA_VCTO         IN  ADMIN_FARMACIA.PRODUCTO.FECHA_VCTO%TYPE,
    V_STOCK              IN  ADMIN_FARMACIA.PRODUCTO.STOCK%TYPE,
    V_STOCK_MIN          IN  ADMIN_FARMACIA.PRODUCTO.STOCK_MIN%TYPE
  )
  IS
  BEGIN
 
    INSERT INTO  ADMIN_FARMACIA.PRODUCTO 
    VALUES (SEQ_PRODUCTO.NEXTVAL,V_COD_CATEGORIA,V_COD_ACCION,V_COD_LABORATORIO,V_NOM_PRODUCTO,V_PRECIO_COSTO,V_PRECIO_UNIDAD,TO_DATE(V_FECHA_VCTO,'YYYY-MM-DD'),V_STOCK,V_STOCK_MIN,1);
    
  END;

  PROCEDURE ACTUALIZAR_PRODUCTOS (
    V_COD_PRODUCTO       IN  ADMIN_FARMACIA.PRODUCTO.COD_PRODUCTO%TYPE,
    V_COD_CATEGORIA      IN  ADMIN_FARMACIA.PRODUCTO.COD_CATEGORIA%TYPE,
    V_COD_ACCION         IN  ADMIN_FARMACIA.PRODUCTO.COD_ACCION%TYPE,
    V_COD_LABORATORIO    IN  ADMIN_FARMACIA.PRODUCTO.COD_LABORATORIO%TYPE,
    V_NOM_PRODUCTO       IN  ADMIN_FARMACIA.PRODUCTO.NOM_PRODUCTO%TYPE,
    V_PRECIO_COSTO       IN  ADMIN_FARMACIA.PRODUCTO.PRECIO_COSTO%TYPE,
    V_PRECIO_UNIDAD      IN  ADMIN_FARMACIA.PRODUCTO.PRECIO_UNIDAD%TYPE,
    V_FECHA_VCTO         IN  ADMIN_FARMACIA.PRODUCTO.FECHA_VCTO%TYPE,
    V_STOCK              IN  ADMIN_FARMACIA.PRODUCTO.STOCK%TYPE,
    V_STOCK_MIN          IN  ADMIN_FARMACIA.PRODUCTO.STOCK_MIN%TYPE
  )
  IS
  BEGIN
 
    UPDATE ADMIN_FARMACIA.PRODUCTO SET
      COD_CATEGORIA       = V_COD_CATEGORIA,
      COD_ACCION          = V_COD_ACCION,
      COD_LABORATORIO     = V_COD_LABORATORIO,
      NOM_PRODUCTO        = V_NOM_PRODUCTO,
      PRECIO_COSTO        = V_PRECIO_COSTO,
      PRECIO_UNIDAD       = V_PRECIO_UNIDAD,
      FECHA_VCTO          = V_FECHA_VCTO,
      STOCK               = V_STOCK,
      STOCK_MIN           = V_STOCK_MIN
    WHERE COD_PRODUCTO    = V_COD_PRODUCTO;
    
  END;
  PROCEDURE ELIMINAR_PRODUCTOS (
    V_COD_PRODUCTO       IN  ADMIN_FARMACIA.PRODUCTO.COD_PRODUCTO%TYPE
  )
  IS
  BEGIN
 
    DELETE FROM ADMIN_FARMACIA.PRODUCTO
    WHERE COD_PRODUCTO    = V_COD_PRODUCTO;
    
  END;
  
END PKGCRUD;


SELECT * FROM ADMIN_FARMACIA.PRODUCTO

--EJECUTAR

BEGIN
ADMIN_FARMACIA.PKGCRUD.CREAR_PRODUCTOS(1,1,1,'AMPOLLAS',20,5,SYSDATE,50,5);
END;

BEGIN
ADMIN_FARMACIA.PKGCRUD.ACTUALIZAR_PRODUCTOS(10,1,1,1,'AMPOLLAS INYECTABLES MODIFICADO',20,5,TO_DATE(SYSDATE,'YYYY-MM-DD'),50,5);
END;



BEGIN
ADMIN_FARMACIA.PKGCRUD.ELIMINAR_PRODUCTOS(10);
END;




