

CREATE OR  REPLACE PROCEDURE ADMIN_FARMACIA.REGISTRAR_VENTA
( 
  P_COD_TIPOCOMPROBANTE     IN ADMIN_FARMACIA.TIPOCOMPROBANTE.COD_TIPOCOMPROBANTE%TYPE,
  P_NUM_SERIE               IN ADMIN_FARMACIA.VENTA.NUM_SERIE%TYPE,
  P_COD_CLIENTE             IN ADMIN_FARMACIA.VENTA.COD_CLIENTE%TYPE,
  P_COD_EMPLEADO            IN ADMIN_FARMACIA.VENTA.COD_EMPLEADO%TYPE,
  P_FECHA_VENTA             IN ADMIN_FARMACIA.VENTA.FECHA_VENTA%TYPE,
  P_TOTAL_DESCUENTO         IN ADMIN_FARMACIA.VENTA.TOTAL_DESCUENTO%TYPE,
  P_IGV                     IN ADMIN_FARMACIA.VENTA.IGV%TYPE,
  P_TOTAL_VENTA             IN ADMIN_FARMACIA.VENTA.TOTAL_VENTA%TYPE,
  P_COD_PRODUCTOArray       IN VARRAY(15) OF NUMBER(4),
  P_CANTIDADArray           IN VARRAY(15) OF NUMBER(4),
  P_PRECIO_UNITARIOArray    IN VARRAY(15) OF NUMBER(10,2),
  P_DESCUENTOArray          IN VARRAY(15) OF NUMBER(10,2),
  P_IGVArray                IN VARRAY(15) OF NUMBER(10,2),
  P_VALORTOTALArray         IN VARRAY(15) OF NUMBER(10,2),
  P_RETORNO                 OUT NUMBER,
  P_MENSAJE                 OUT VARCHAR2(50)
) 
IS 
  V_COD_PRODUCTO  P_COD_PRODUCTOArray;
	V_CANTIDAD      P_CANTIDADArray;
  V_PRECIO        P_PRECIO_UNITARIOArray;
  V_DESCUENTO     P_DESCUENTOArray;
  V_IGV           P_IGVArray;
  V_VALORTOTAL    P_VALORTOTALArray;
  
  V_CODVENTA NUMBER;
BEGIN 
  
  P_RETORNO  := 1;
  P_MENSAJE  := 'PROCESO CORRECTO';

  SELECT ADMIN_FARMACIA.SEQ_DETALLE_VENTA.NEXTVAL INTO V_CODVENTA FROM DUAL;

  --INASERTAR VENTAS
  INSERT INTO  ADMIN_FARMACIA.VENTA VALUES (V_CODVENTA,P_COD_TIPOCOMPROBANTE,P_NUM_SERIE,P_COD_CLIENTE,P_COD_EMPLEADO,P_FECHA_VENTA,P_TOTAL_DESCUENTO,P_IGV,P_TOTAL_VENTA);

  --INASERTAR DETALLE DE VENTAS 
  	FOR i IN 1 .. V_COD_PRODUCTO.COUNT LOOP
    
      INSERT INTO  ADMIN_FARMACIA.DETALLE_VENTA VALUES (SEQ_DETALLE_VENTA.NEXTVAL,V_CODVENTA,P_NUM_SERIE,V_COD_PRODUCTO(i),V_CANTIDAD(i),V_PRECIO(i),V_DESCUENTO(i),V_IGV(i),V_VALORTOTAL(i));
      
    END LOOP;

EXCEPTION 
  WHEN OTHERS THEN
    P_RETORNO  := 0;
    P_MENSAJE  := 'PROCESO CON ERRORES';
 -- WHEN No_Data_Found THEN 
  --  DBMS_Output.Put_Line( 'Código no existe.' ); 
END; 
/

call ADMIN_FARMACIA.REGISTRAR_VENTA
(
  P_COD_TIPOCOMPROBANTE   = 1,
  P_NUM_SERIE             = 'F001-500',
  P_COD_CLIENTE           = 1,
  P_COD_EMPLEADO          = 1,
  P_FECHA_VENTA           = TO_DATE(SYSDATE,'YYYY-MM-DD'),
  P_TOTAL_DESCUENTO       = 20,
  P_IGV                   = 10,
  P_TOTAL_VENTA           = 30,
  P_COD_PRODUCTOArray (1,2,3),
  P_CANTIDADArray(2,1,1),
  P_PRECIO_UNITARIOArray(2,3,4),
  P_DESCUENTOArray(0,0,0),
  P_IGVArray(1,2,4),
  P_VALORTOTALArray(10,2,5),
  0,
  'M'
);
